- name: Run scraper
  env:
    GAS_ENDPOINT: ${{ secrets.GAS_ENDPOINT }}
  run: node api/scrape.js
- name: Cache node modules
  uses: actions/cache@v4
  with:
    path: ~/.npm
    key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
    restore-keys: |
      ${{ runner.os }}-npm-cache-
