# .github/workflows/scrape.yml
name: Run Scraper
on:
  workflow_dispatch:  # 수동 실행
jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: node api/scrape.js
